import { lazyWithRetry } from "@/lib/lazyWithRetry";

export const Dashboard = lazyWithRetry(() => import("@/pages/Dashboard"));
export const Leads = lazyWithRetry(() => import("@/pages/Leads"));
export const Students = lazyWithRetry(() => import("@/pages/Students"));
export const Courses = lazyWithRetry(() => import("@/pages/Courses"));
export const Batches = lazyWithRetry(() => import("@/pages/Batches"));
export const PaymentLinksPage = lazyWithRetry(() => import("@/pages/payment-links/PaymentLinksPage"));
export const PaymentLinksRecordsPage = lazyWithRetry(() => import("@/pages/payment-links/PaymentLinksRecordsPage"));
export const Team = lazyWithRetry(() => import("@/pages/Team"));
export const SettingsPage = lazyWithRetry(() => import("@/pages/settings/SettingsPage"));
export const Tasks = lazyWithRetry(() => import("@/pages/Tasks"));
export const Apply = lazyWithRetry(() => import("@/pages/Apply"));
export const PrivacyPolicyPage = lazyWithRetry(() => import("@/pages/legal/PrivacyPolicyPage"));
export const TermsOfServicePage = lazyWithRetry(() => import("@/pages/legal/TermsOfServicePage"));
export const MyReferrals = lazyWithRetry(() => import("@/pages/MyReferrals"));
export const ReferralAnalytics = lazyWithRetry(() => import("@/pages/ReferralAnalytics"));
export const FormLeads = lazyWithRetry(() => import("@/pages/FormLeads"));
export const ImportedLeads = lazyWithRetry(() => import("@/pages/ImportedLeads"));
export const LeadHistory = lazyWithRetry(() => import("@/pages/LeadHistory"));
export const FormLeadHistory = lazyWithRetry(() => import("@/pages/FormLeadHistory"));
export const AssignedLeads = lazyWithRetry(() => import("@/pages/AssignedLeads"));
export const DailyReports = lazyWithRetry(() => import("@/pages/DailyReports"));
export const DailyReportsAnalytics = lazyWithRetry(() => import("@/pages/DailyReportsAnalytics"));
export const Notifications = lazyWithRetry(() => import("@/pages/Notifications"));
export const MarketingDashboard = lazyWithRetry(() => import("@/pages/MarketingDashboard"));
export const MarketingPortal = lazyWithRetry(() => import("@/pages/MarketingPortal"));
export const MarketingPortalDashboard = lazyWithRetry(() => import("@/pages/MarketingPortalDashboard"));
export const EmailAnalytics = lazyWithRetry(() => import("@/pages/EmailAnalytics"));
export const WhatsAppPortal = lazyWithRetry(() => import("@/pages/WhatsAppPortal"));
export const WhatsAppAnalytics = lazyWithRetry(() => import("@/pages/WhatsAppAnalytics"));
export const Holidays = lazyWithRetry(() => import("@/pages/Holidays"));
export const Trash = lazyWithRetry(() => import("@/pages/Trash"));
export const OfferLetters = lazyWithRetry(() => import("@/pages/OfferLetters"));
export const CertificatesPage = lazyWithRetry(() => import("@/pages/CertificatesPage"));
export const PayslipPage = lazyWithRetry(() => import("@/pages/payslip/PayslipPage"));
export const FormsManagerPage = lazyWithRetry(() => import("@/pages/FormsManagerPage"));
export const FormApiIntegrationsPage = lazyWithRetry(() => import("@/pages/FormApiIntegrationsPage"));
export const SuperAdminPanel = lazyWithRetry(() => import("@/pages/SuperAdminPanel"));
export const SuperAdminOrgDashboard = lazyWithRetry(() => import("@/pages/SuperAdminOrgDashboard"));
export const NotFound = lazyWithRetry(() => import("@/pages/NotFound"));
export const HRDashboard = lazyWithRetry(() => import("@/pages/hr/HRDashboard"));
export const HRMyLeads = lazyWithRetry(() => import("@/pages/hr/MyLeads"));
export const HRAssignedLeads = lazyWithRetry(() => import("@/pages/hr/AssignedLeads"));
export const HRTasks = lazyWithRetry(() => import("@/pages/hr/Tasks"));
export const HRReports = lazyWithRetry(() => import("@/pages/hr/Reports"));
export const HRNotifications = lazyWithRetry(() => import("@/pages/hr/Notifications"));
export const HRHolidays = lazyWithRetry(() => import("@/pages/hr/Holidays"));
export const HRCommunicationsPage = lazyWithRetry(() => import("@/pages/hr/HRCommunicationsPage"));
export const HRLeadsPage = lazyWithRetry(() => import("@/pages/leads/HRLeadsPage"));
export const CommunicationsHubPage = lazyWithRetry(() => import("@/pages/communications/CommunicationsHubPage"));
export const WhatsAppInboxPage = lazyWithRetry(() => import("@/pages/communications/WhatsAppInboxPage"));
export const CommunicationsAdminPage = lazyWithRetry(() => import("@/pages/communications/CommunicationsAdminPage"));
export const OrgWhatsAppSetupPage = lazyWithRetry(() => import("@/pages/communications/OrgWhatsAppSetupPage"));
export const MetaPartnerPage = lazyWithRetry(() => import("@/pages/communications/MetaPartnerPage"));
export const TemplateLibraryPage = lazyWithRetry(() => import("@/pages/communications/TemplateLibraryPage"));
export const FresherSalaryTrackerPage = lazyWithRetry(() => import("@/pages/FresherSalaryTrackerPage"));
export const CallLogPage = lazyWithRetry(() => import("@/pages/sales/CallLogPage"));
export const AssessmentsAdminPage = lazyWithRetry(() => import("@/pages/AssessmentsAdminPage"));
export const PeaklyyAssessmentPage = lazyWithRetry(() => import("@/pages/PeaklyyAssessmentPage"));

/** Certificate verify is a named export on CertificatesPage. */
export const CertificateVerifyPage = lazyWithRetry(() =>
  import("@/pages/CertificatesPage").then((m) => ({ default: m.CertificateVerifyPage })),
);
